### ISSUE TITLE
报错'PostgresDatabaseConnector' object has no attribute 'data_interactor'

### ISSUE THREAD

**Issue by xyc888** [alibaba/pilotscope#6]
您好大佬，我在按照algorithm_examples/Index/index_selection_evaluation中的readme安装，在执行python3 -m selection benchmark_results/tpch_wo_2_17_20/config.json这步的时候为什么会报这个错误'PostgresDatabaseConnector' object has no attribute 'data_interactor'，但是我看PostgresDatabaseConnector中确实没有data_interactor属性，请问可能是什么原因呀，另外index_selection_evaluatio目录下好像缺少hypopg和tpch-kit这两个文件夹，是我自己从别处下载的，是否和这个有关
```
xyc@xyc-virtual-machine:~/桌面/pilotscope/algorithm_examples/Index/index_select
ion_evaluation$ python3 -m selection benchmark_results/tpch_wo_2_17_20/config.json
2024-05-17 22:50:39,029 - root - DEBUG - Init IndexSelection
2024-05-17 22:50:39,029 - root - INFO - Starting Index Selection Evaluation
2024-05-17 22:50:39,029 - root - INFO - Using config file benchmark_results/tpch_wo_2_17_20/config.json
2024-05-17 22:50:39,029 - root - DEBUG - Database connector created: None
2024-05-17 22:50:39,032 - root - INFO - Postgres: Set random seed `SELECT setseed(0.17)`
2024-05-17 22:50:39,033 - root - DEBUG - Postgres connector created: None
2024-05-17 22:50:39,033 - root - DEBUG - Database with given scale factor already existing
2024-05-17 22:50:39,034 - root - DEBUG - Database connector created: indexselection_tpch___1
2024-05-17 22:50:39,036 - root - INFO - Postgres: Set random seed `SELECT setseed(0.17)`
2024-05-17 22:50:39,037 - root - DEBUG - Postgres connector created: indexselection_tpch___1
2024-05-17 22:50:39,037 - root - INFO - Generating TPC-H Queries
2024-05-17 22:50:39,037 - root - DEBUG - No need to run make
2024-05-17 22:50:39,043 - root - INFO - Queries generated
2024-05-17 22:50:39,044 - root - INFO - Dropping indexes
2024-05-17 22:50:39,047 - root - INFO - Postgres: Run `analyze`
2024-05-17 22:50:39,151 - root - INFO - Dropping indexes
2024-05-17 22:50:39,152 - root - INFO - Create new database connector (closing old)
2024-05-17 22:50:39,152 - root - DEBUG - Database connector closed: indexselection_tpch___1
2024-05-17 22:50:39,153 - root - DEBUG - Database connector created: indexselection_tpch___1
2024-05-17 22:50:39,155 - root - INFO - Postgres: Set random seed `SELECT setseed(0.17)`
2024-05-17 22:50:39,156 - root - DEBUG - Postgres connector created: indexselection_tpch___1
2024-05-17 22:50:39,156 - root - DEBUG - Init selection algorithm
2024-05-17 22:50:39,156 - root - INFO - Dropping indexes
2024-05-17 22:50:39,159 - root - DEBUG - Init cost evaluation
2024-05-17 22:50:39,159 - root - INFO - Cost estimation with actual_runtimes
2024-05-17 22:50:39,159 - root - DEBUG - Init WhatIfIndexCreation
2024-05-17 22:50:39,159 - root - INFO - Running algorithm {'name': 'extend', 'parameters': {'budget_MB': 250, 'max_index_width': 2, 'benchmark_name': 'tpch', 'min_cost_improvement': 1.003}, 'timeout': 300}
2024-05-17 22:50:39,159 - root - INFO - Calculating best indexes Extend
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xyc/桌面/pilotscope/algorithm_examples/Index/index_selection_evaluation/selection/__main__.py", line 4, in <module>
    index_selection.run()  # pragma: no cover
  File "/home/xyc/桌面/pilotscope/algorithm_examples/Index/index_selection_evaluation/selection/index_selection_evaluation.py", line 59, in run
    self._run_algorithms(config_file)
  File "/home/xyc/桌面/pilotscope/algorithm_examples/Index/index_selection_evaluation/selection/index_selection_evaluation.py", line 155, in _run_algorithms
    indexes, what_if, cost_requests, cache_hits = self._run_algorithm(
  File "/home/xyc/桌面/pilotscope/algorithm_examples/Index/index_selection_evaluation/selection/index_selection_evaluation.py", line 206, in _run_algorithm
    indexes = algorithm.calculate_best_indexes(self.workload)
  File "/home/xyc/桌面/pilotscope/algorithm_examples/Index/index_selection_evaluation/selection/selection_algorithm.py", line 36, in calculate_best_indexes
    indexes = self._calculate_best_indexes(workload)
  File "/home/xyc/桌面/pilotscope/algorithm_examples/Index/index_selection_evaluation/selection/algorithms/extend_algorithm.py", line 49, in _calculate_best_indexes
    current_cost = self.cost_evaluation.calculate_cost(
  File "/home/xyc/桌面/pilotscope/algorithm_examples/Index/index_selection_evaluation/selection/cost_evaluation.py", line 77, in calculate_cost
    pilot_total_cost = self.pilot_calculate_cost(workload, indexes)
  File "/home/xyc/桌面/pilotscope/algorithm_examples/Index/index_selection_evaluation/selection/cost_evaluation.py", line 104, in pilot_calculate_cost
    data_interactor = self.db_connector.data_interactor
AttributeError: 'PostgresDatabaseConnector' object has no attribute 'data_interactor'
```

**Comment by duoyw** [comment]
Pilotscope只是使用index_selection_evaluation的部分内容作为示例，因此只对部分代码做了兼容。你使用的超过了我们兼容的范围，可以直接参考index_selection_evaluation的原仓库安装。
